"""Ticker universes for the scanner. NSE tickers use the .NS suffix (yfinance)."""

NIFTY50 = [
    "RELIANCE.NS", "TCS.NS", "HDFCBANK.NS", "ICICIBANK.NS", "INFY.NS",
    "HINDUNILVR.NS", "ITC.NS", "SBIN.NS", "BHARTIARTL.NS", "BAJFINANCE.NS",
    "KOTAKBANK.NS", "LT.NS", "AXISBANK.NS", "ASIANPAINT.NS", "MARUTI.NS",
    "HCLTECH.NS", "SUNPHARMA.NS", "TITAN.NS", "ULTRACEMCO.NS", "WIPRO.NS",
    "NESTLEIND.NS", "BAJAJFINSV.NS", "ONGC.NS", "NTPC.NS", "POWERGRID.NS",
    "TATAMOTORS.NS", "TATASTEEL.NS", "ADANIENT.NS", "ADANIPORTS.NS", "JSWSTEEL.NS",
    "M&M.NS", "COALINDIA.NS", "HINDALCO.NS", "GRASIM.NS", "INDUSINDBK.NS",
    "DRREDDY.NS", "CIPLA.NS", "BAJAJ-AUTO.NS", "EICHERMOT.NS", "HEROMOTOCO.NS",
    "BRITANNIA.NS", "DIVISLAB.NS", "APOLLOHOSP.NS", "TATACONSUM.NS", "BPCL.NS",
    "SBILIFE.NS", "HDFCLIFE.NS", "TECHM.NS", "LTIM.NS", "SHRIRAMFIN.NS",
]

# Nifty Next 50 (large/mid caps) — extends the scan universe.
NIFTY_NEXT50 = [
    "ADANIGREEN.NS", "ADANIPOWER.NS", "AMBUJACEM.NS", "BANKBARODA.NS", "BERGEPAINT.NS",
    "BOSCHLTD.NS", "CHOLAFIN.NS", "COLPAL.NS", "DABUR.NS", "DLF.NS",
    "GAIL.NS", "GODREJCP.NS", "HAVELLS.NS", "ICICIGI.NS", "ICICIPRULI.NS",
    "IOC.NS", "IRCTC.NS", "JINDALSTEL.NS", "MARICO.NS", "MCDOWELL-N.NS",
    "MOTHERSON.NS", "MUTHOOTFIN.NS", "NAUKRI.NS", "PIDILITIND.NS", "PNB.NS",
    "SAIL.NS", "SIEMENS.NS", "SRF.NS", "TORNTPHARM.NS", "TRENT.NS",
    "TVSMOTOR.NS", "UNITDSPR.NS", "VBL.NS", "VEDL.NS", "ZOMATO.NS",
    "ZYDUSLIFE.NS", "AUROPHARMA.NS", "BANDHANBNK.NS", "BIOCON.NS", "CANBK.NS",
    "GMRINFRA.NS", "INDIGO.NS", "LICI.NS", "PAGEIND.NS", "PEL.NS",
    "PFC.NS", "RECLTD.NS", "TATAPOWER.NS", "UPL.NS", "YESBANK.NS",
]

UNIVERSES = {
    "nifty50": NIFTY50,
    "nifty100": NIFTY50 + NIFTY_NEXT50,
}
